### ISSUE TITLE
related repository

### ISSUE THREAD

**Issue by shadiakiki1986** [Potherca/flysystem-readonly-git-adapter#3]
Hey there. I noticed you had 4 different repositories about flysystem-git adapters, including a github-specific one. I just finished a first draft of my own adapter [here](https://github.com/shadiakiki1986/flysystem-git). I'll be glad if you find it of use, or if you have any propositions.

**Comment by Potherca** [comment]
My first suggestion would be to rename the project to `flysytem-node-git-rest-api` (or something similar) as to not confuse it with a regular git adapter.

Other than that the code seems to contain some strange logic here and there. I can give you a more in-depth review if you like.
